# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 572)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.contact_list = QtWidgets.QListView(self.centralwidget)
        self.contact_list.setGeometry(QtCore.QRect(20, 20, 211, 501))
        self.contact_list.setObjectName("contact_list")
        self.message_list = QtWidgets.QListView(self.centralwidget)
        self.message_list.setGeometry(QtCore.QRect(240, 20, 541, 361))
        self.message_list.setObjectName("message_list")
        self.edit_message = QtWidgets.QTextEdit(self.centralwidget)
        self.edit_message.setGeometry(QtCore.QRect(240, 390, 431, 131))
        self.edit_message.setObjectName("edit_message")
        self.send_button = QtWidgets.QPushButton(self.centralwidget)
        self.send_button.setGeometry(QtCore.QRect(684, 430, 81, 51))
        self.send_button.setObjectName("send_button")
        self.contacts_label = QtWidgets.QLabel(self.centralwidget)
        self.contacts_label.setGeometry(QtCore.QRect(20, 0, 151, 16))
        self.contacts_label.setObjectName("contacts_label")
        self.message_label = QtWidgets.QLabel(self.centralwidget)
        self.message_label.setGeometry(QtCore.QRect(240, 0, 151, 16))
        self.message_label.setObjectName("message_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.main_menu = QtWidgets.QMenu(self.menubar)
        self.main_menu.setObjectName("main_menu")
        self.contact_menu = QtWidgets.QMenu(self.menubar)
        self.contact_menu.setObjectName("contact_menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.exit_menu = QtWidgets.QAction(MainWindow)
        self.exit_menu.setMenuRole(QtWidgets.QAction.QuitRole)
        self.exit_menu.setObjectName("exit_menu")
        self.add_contact = QtWidgets.QAction(MainWindow)
        self.add_contact.setObjectName("add_contact")
        self.remove_contact = QtWidgets.QAction(MainWindow)
        self.remove_contact.setObjectName("remove_contact")
        self.main_menu.addAction(self.exit_menu)
        self.contact_menu.addAction(self.add_contact)
        self.contact_menu.addAction(self.remove_contact)
        self.menubar.addAction(self.main_menu.menuAction())
        self.menubar.addAction(self.contact_menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MyMessenger - BETA"))
        self.send_button.setText(_translate("MainWindow", "Отправить"))
        self.contacts_label.setText(_translate("MainWindow", "Ваши контакты"))
        self.message_label.setText(_translate("MainWindow", "История сообщений"))
        self.main_menu.setTitle(_translate("MainWindow", "Меню"))
        self.contact_menu.setTitle(_translate("MainWindow", "Контакты"))
        self.exit_menu.setText(_translate("MainWindow", "Выход"))
        self.add_contact.setText(_translate("MainWindow", "Добавить контакт"))
        self.remove_contact.setText(_translate("MainWindow", "Удалить контакт"))
